### ISSUE TITLE
ERROR_FAILED_TO_VERIFY_JWT

### ISSUE THREAD

**Issue by dvidal49** [tschoffelen/mapkit-jwt#2]
Hello,
I tested your library and I get a JWT TOKEN.
But when I test it, I have an error after identifying myself in the Apple connection popup.
I have this error: ERROR_FAILED_TO_VERIFY_JWT

However, I put my private key, my key ID and team identifier

Do you have an idea of ​​the problem?
Thanks for your help.
David.

**Comment by tschoffelen** [comment]
Hi David,

Could you give me some more info about how you're using the generated token?

Cheers!

**Comment by dvidal49** [comment]
Hi !
I use it for Apple Musickit.
With:
      MusicKit.configure ({
        developerToken: 'XXXX',
        app: {...

**Comment by dvidal49** [comment]
Hi Thomas,
Have you an idea for my problem ?
Cheers

**Comment by tschoffelen** [comment]
This usually points to an incorrectly specified team ID or key ID, or a key that hasn't been authorized for use with MusicKit.

That being said, this library is specifically geared toward MapKit, not MusicKit, although there shouldn't be any differences in the way of authentication as far as I know.

**Comment by dvidal49** [comment]
Thank you Thomas
I recheck it all over again.
